
// This is a placeholder API client module that would normally connect to a backend
// For now, it just returns mock data

// Generate a summary for a YouTube video
export const generateSummary = async ({ videoId }: { videoId: string }): Promise<{ summary: string }> => {
  console.log(`Generating summary for video ${videoId}`);
  
  // Simulate API call with a delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  return {
    summary: `This is an AI-generated summary of the video with ID ${videoId}. In a real application, this would be generated by an AI model that analyzes the video content. The summary would include key points, main ideas, and important information from the video to help users quickly understand what the video is about without having to watch it in its entirety.

This summary might also include timestamps for different sections of the video, allowing users to jump directly to the parts they're most interested in. Additionally, it could highlight any particularly insightful or valuable segments.

For educational content, the summary might emphasize learning objectives and key takeaways. For tutorial videos, it might break down the steps in an easy-to-follow format.`
  };
};

// Send a message to the AI assistant
export const sendMessage = async ({ videoId, message }: { videoId: string; message: string }): Promise<{ content: string }> => {
  console.log(`Sending message for video ${videoId}: ${message}`);
  
  // Simulate API call with a delay
  await new Promise(resolve => setTimeout(resolve, 800));
  
  // Return a simple response based on the input message
  let response = `This is an AI response about video ${videoId}. `;
  
  if (message.toLowerCase().includes('summary')) {
    response += "I can generate a summary of this video for you. Would you like me to do that?";
  } else if (message.toLowerCase().includes('explain')) {
    response += "I'd be happy to explain concepts from this video. Which part would you like me to focus on?";
  } else if (message.toLowerCase().includes('time') || message.toLowerCase().includes('timestamp')) {
    response += "I can help you find specific timestamps in this video. What topic are you looking for?";
  } else {
    response += "I'm here to help you understand and analyze this video. You can ask me to summarize content, explain concepts, or find specific topics in the video.";
  }
  
  return {
    content: response
  };
};
